### ISSUE TITLE
Remove CircleCI Integration

### ISSUE THREAD

**Issue by devppjr** [thumbor-community/redis#11]
Since https://github.com/thumbor-community/redis/pull/8 was removed circleCi integration and added github actions. I think we can remove circleCI integration hosted in https://app.circleci.com/pipelines/github/thumbor-community/redis. 

What u think guys ? @masom @Bladrak

**Comment by Bladrak** [comment]
Yes, you're right. I've stopped the builds on circle :) Should be alright now!
